### ISSUE TITLE
Archive View on Page 2

### ISSUE THREAD

**Issue by ms-carterk** [birgire/wp-combine-queries#12]
Upon setting this up when I hit page/2 for any loop I get a 404 page.

Does this work when using multipage archives and am I missing something or does this feature not exist?

**Comment by birgire** [comment]
Hi @ms-carterk 

Are you using a secondary WP_Query to handle the pagination?

It's better to use the pre_get_posts to modify the main query instead.

**Comment by ms-carterk** [comment]
Yes it is thank you!
