### ISSUE TITLE
Fatal error on Install

### ISSUE THREAD

**Issue by bichonnages** [birgire/wp-combine-queries#15]
Hello,

I have been trying to install your plugin on my wordpress install (4.7) and I cannot activate it (Parse error: syntax error, unexpected T_STRING in /home/gmemzeuq/new/wp-content/plugins/wp-combine-queries-master/combined-query.php on line 13).

Is there any way you could help?
Thanks for your great work.

**Comment by birgire** [comment]
@bichonnages 

I guess you have PHP 5.2 or less, since it doesn't support namespaces.

Glad to hear you find it useful.
