### ISSUE TITLE
Subsequent queries after a query with combine_queries are broken

### ISSUE THREAD

**Issue by Suranex** [birgire/wp-combine-queries#24]
The following lines broke subsequent queries which are not use `combined_query` (after a query with `combined_query `was used) because the filter are now always applied. The filter `posts_request `and `posts_orderby` should only be added by `pre_get_posts`, 

https://github.com/birgire/wp-combine-queries/blob/5fc550f07ef08a057c9ad62a452e00e6bb04091e/includes/Main.php#L107-L108

**Comment by birgire** [comment]
thank you @Suranex 
I'm unable to fix it for now, but pr and unit tests are welcomed

**Comment by birgire** [comment]
Should be fixed in version 1.2.2
