### ISSUE TITLE
Suggestion: Preserving unique sorting in subqueries

### ISSUE THREAD

**Issue by anekola** [birgire/wp-combine-queries#25]
First – thanks for this plugin! One of my uses is on an event listing page to first show upcoming events in ASC order and then show past events in DESC order. But I was having a hell of a time getting them to actually sort correctly! The dates within each query were always jumbled. 

I took some guidance from this StackOverflow posts: https://stackoverflow.com/questions/30192885/how-to-sort-data-in-mysql-union-subquery

Essentially, it claimed that the outer query would negate any sorting of inner queries. It was useful to assign an ID to the records in each subquery, to preserve that order, and then reiterate the sorting with the outer query. This is messy, but it worked:

```
// Needed a global variable here to increment.
$cq_sortfield_count = 0;

// Modify sub fields:
add_filter( 'cq_sub_fields', $callback = function( $fields ) {
	global $cq_sortfield_count;
	$cq_sortfield_count++;
	// Create a new field with an ID for each query.
	return $fields . ', meta_value,  "' . $cq_sortfield_count . '" AS sortfield';
});

// Modify combined ordering:
add_filter( 'cq_orderby', function( $orderby ) {
	$current_time = time() - ( 5 * 60 * 60 );
	//  Here we first sort by the new field which then allows a second layer of sorting within the two groups.
	return 'sortfield ASC, IF( combined.meta_value > ' . $current_time . ', combined.meta_value, 0) ASC, IF( combined.meta_value <= ' . $current_time . ', combined.meta_value, null) DESC';
});
```

Just sharing in case this helps at all!

**Comment by birgire** [comment]
Great, 

thanks @anekola  for sharing your creative solution 

and all your extensive research. 

I'm sure it will be helpful to others.

(I will keep it open for few weeks)
