### ISSUE TITLE
Recently combined queries started including ACF field groups

### ISSUE THREAD

**Issue by gavin310** [birgire/wp-combine-queries#29]
I've been combining 3 sub queries on a site with no problems until recently. Sometimes one or two of the sub queries are empty arrays, but that hasn't posted a problem until recently. In the last week or so we've had issues with the queries returning ACF field group posts. I still have no idea why, as I'm specifying a particular post type in the sub queries. To fix this I needed to not include the empty arrays in the 'combined_query' argument array.

Previously my code looked like this:

```
$query = new WP_Query( array(
	'combined_query' => array(
		'args' 				=> array( $sub_query1, $sub_query2, $sub_query3 ),
		'orderby' 			=> 'none',
		'posts_per_page' 	=> $per_page,
		'paged' 			=> $cur_page,
	),
) );
```

And now it looks like this:

```
$combined_queries = [];
if ( ! empty( $sub_query1 ) ) {
	array_push( $combined_queries, $sub_query1 );
}
if ( ! empty( $sub_query2 ) ) {
	array_push( $combined_queries, $sub_query2 );
}
if ( ! empty( $sub_query3 ) ) {
	array_push( $combined_queries, $sub_query3 );
}

$query = new WP_Query( array(
	'combined_query' => array(
		'args' 				=> $combined_queries,
		'orderby' 			=> 'none',
		'posts_per_page' 	=> $per_page,
		'paged' 			=> $cur_page,
	),
) );
```

Hopefully this helps anyone facing the same issue.

**Comment by birgire** [comment]
Thanks for sharing @gavin310 

At the moment I think this is expected since WP_Query supports empty array input resulting in default values being used.

I'm marking this as a docs/example and closing.

Welcome to re-open if you see this more as a bug.
