### ISSUE TITLE
Parse error: syntax error, unexpected '[' in /includes/Main.php on line 14

### ISSUE THREAD

**Issue by ms-carterk** [birgire/wp-combine-queries#4]
Parse error: syntax error, unexpected '[' in /wp-content/plugins/wp-combine-queries-master/includes/Main.php on line 14

**Comment by ms-carterk** [comment]
Nevermind Server was outputting the wrong php version

**Comment by birgire** [comment]
ok thanks for reporting back 

@ms-carterk
